### ISSUE TITLE
FDISK does not write BootEasy MBR

### ISSUE THREAD

**Issue by shidel** [FDOS/fdisk#11]
Created from [GitLab Archive FDISK Issue 3](https://gitlab.com/FreeDOS/base/fdisk/-/issues/3)

Trying to write the BootEasy MBR to disk just prints 

```
C:\>fdisk /bmbr 1
Syntax Error...Operation Terminated.
C:\>fdisk /mbr 1
C:\>
```

**Comment by boeckmann** [comment]
That seems to be completely disabled at the moment.  I do not know why, but my guess is someone disabled it because BootEasy does not support Extended BIOS functions (LBA). It could be re-enabled fairly easy. It currently gets linked in anyway as dead code. If we do not re-enable I would at least throw it out of the executable (we can leave it in the repository if someone looks at it for making it LBA capable).

**Comment by boeckmann** [comment]
As of 1.3.5 it is not linked into the binary anymore (it was dead code).

**Comment by shidel** [comment]
:-)
