### ISSUE TITLE
Turkish translation

### ISSUE THREAD

**Issue by boeckmann** [FDOS/fdisk#57]

**Comment by bitigchi** [comment]
Hello there! I will open another PR soon with some improvements and terminology more in-line with the current other FDOS components.

**Comment by cardpuncher** [comment]
Hey Emir, I would have a few questions regarding your translation:

- Firstly, the word "Bölüntü" for partition. I tend to use "Bölüm" for that, and Wikipedia's relevant [article](https://tr.wikipedia.org/wiki/Disk_b%C3%B6l%C3%BCmlendirme) in Turkish uses the same word as does the FreeDOS installer currently. Are you sure about that word?
- I would use "GNU Genel Kamu Lisansı 2. sürümü kapsamında lisanslanmıştır." for line number 0.201.
- Just noticed that there's a typo in "6.2:Kayıtlı dosydan MBR yükle (bölüntüler ve kod)." (dosydan).
- I would leave a FDISK in Turkish in the first comment lines for programmers so that they can immediately know what language this is.

Apart from that, it looks perfect to me. Thank you for your hard work.

**Comment by mateuszviste** [comment]
I would indeed recommend leaving the language fully apparent in the comment, otherwise it's difficult for Turkish-ignorant people like me to guess what language this is.

About vocabulary: I suggest looking at how MS named things in their FDISK. Was there ever an MS-DOS in Turkish? If not, then maybe the FDISK tool from a Turkish Windows 9x has been translated? It is not about copying MS of course, simply about using a common vocabulary to avoid confusion.

**Comment by bitigchi** [comment]
@cardpuncher, I will fix the last three issues soon. About the first one; it's one of the best solutions to the cluster-mess of the terminology rounding around "bölüm". One way or another for years; volume, section, and partition has been translated with bölüm, or with additions to it. macOS fixes this with bölüntü, and to think about it, it's the perfect solution. It encapsulates the size and layout hierarchy completely and implies it perfectly. I have migrated KDE translations to it as well, and works great. I shall note that, macOS translations are impeccably good compared to Windows, which is somehow in a worse state than Win95 back in the day.

@mateuszviste, DOS and Windows has shipped with Turkish translations since Windows 3.1. While these translations are not that much different, I find them definitely more concise and lean. Although I enjoy using old Windows versions, there is definitely room for improvements, mostly stemming from having the terminology being in its infancy.

**Comment by boeckmann** [comment]
I @cardpuncher, @bitigchi I would like to add you to the credits file. How do you want to be listed? With your real name or some pseudonym? Or even not at all?

**Comment by bitigchi** [comment]
@boeckmann "Emir SARI" is good. Thank you very much!

**Comment by cardpuncher** [comment]
On 9.07.2023 18:22, Emir SARI wrote:
> @cardpuncher <https://github.com/cardpuncher>, I will fix the last three 
> issues soon. About the first one; it's one of the best solutions to the 
> cluster-mess of the terminology rounding around "bölüm". 

I see two solutions to the problem: either we use "bölüntü", but then 
we'd need to grep all other programs' Turkish translations for "bölüm" 
and change them too, or we go with "bölüm" in this file, for consistency 
purposes.

I downloaded the fd-nls-master tarball and extracted it. Then a

grep -r bölüm

returned a bunch of results...

@boeckmann Berki Yenigün would be nice for the credits, thank you!

**Comment by bitigchi** [comment]
@cardpuncher, you're absolutely right. It's been a while since I've my updated nls repository. :)

**Comment by boeckmann** [comment]
I think this can be considered complete? Than I would close the issue.

**Comment by bitigchi** [comment]
Oh yes, definitely. Thanks for all your help.
